services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mike123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    environment:
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=mike123
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
