# Generated by Django 5.2.3 on 2025-08-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='status',
        ),
    ]
